package kedai;
// Generated 14/11/2018 7:12:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idCust;
     private String cust;
     private Set orderses = new HashSet(0);

    public Customer() {
    }

    public Customer(String cust, Set orderses) {
       this.cust = cust;
       this.orderses = orderses;
    }
   
    public Integer getIdCust() {
        return this.idCust;
    }
    
    public void setIdCust(Integer idCust) {
        this.idCust = idCust;
    }
    public String getCust() {
        return this.cust;
    }
    
    public void setCust(String cust) {
        this.cust = cust;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


