package kedai;
// Generated 14/11/2018 7:12:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer idItem;
     private String item;
     private Long price;
     private Set orderses = new HashSet(0);

    public Item() {
    }

	
    public Item(String item) {
        this.item = item;
    }
    public Item(String item, Long price, Set orderses) {
       this.item = item;
       this.price = price;
       this.orderses = orderses;
    }
   
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


